POSIX shell compliant with compacted syntax

diff --git a/git-credential-lastpass b/git-credential-lastpass
--- a/git-credential-lastpass
+++ b/git-credential-lastpass
@@ -1,269 +1,138 @@
-#!/usr/bin/env bash
+#!/bin/sh
 
-# A credential helper for git to retrieve usernames and passwords from lastpass.
+# A git-credential compatible helper to retrieve usernames and passwords from lastpass.
 
 # 1. Put this somewhere in your path.
 # 2. git config --global credential.helper lastpass
 
-# see documentation
-
-# https://git-scm.com/docs/git-credential
 # https://git-scm.com/docs/gitcredentials
+# https://git-scm.com/docs/git-credential
 
 # https://github.com/lastpass/lastpass-cli/blob/master/lpass.1.txt
 
 # parse operation from command line
 # optionaly get lastpass username/email address
-if [ "$1" = "-l" ]; then
-    lpassuser="$2"
-    shift
-    shift
-fi
-if [ $# -eq 0 ]; then
-    echo "$0: missing operation" >&2
-    exit
-fi
-if [ $# -gt 1 ]; then
-    echo "$0: unexpected command line arguments '$*'" >&2
-    exit
-fi
-if [ "$1" != "get" ] && [ "$1" != "store" ] && [ "$1" != "erase" ]; then
-    # silently ignore uninmplemented operations
-    exit
-fi
-operation="$1"
+test "$1" = "-l" && lpassuser="$2" && shift && shift
+test $# -eq 0 && echo "$0: missing operation" >&2 && exit
+test $# -gt 1 && echo "$0: unexpected command line arguments '$*'" >&2 && exit
+operation=$1
+# silently ignore uninmplemented operations
+case $operation in get | store | erase) ;; *) exit ;; esac
 
 # parse attributes from stdin
-while read -r line && [ -n "$line" ]; do
-    name=$(
-        echo "$line" | cut -d '=' -f 1 -s
-    )
-    value=$(
-        echo "$line" | cut -d '=' -f 2 -s
-    )
-    case "$name" in
-    "url")
-        param_url="$value"
+while IFS='=' read -r key value; do
+    case $key in
+    protocol | host | path | username | password)
+        eval "$key"="$value"
         ;;
-    "protocol")
-        param_protocol="$value"
-        ;;
-    "host")
-        param_host="$value"
-        ;;
-    "path")
-        param_path="$value"
-        ;;
-    "username")
-        param_username="$value"
-        ;;
-    "password")
-        param_password="$value"
+    url)
+        # extract protocol
+        case $value in *://*) protocol=${value%%://*} ;; esac
+        test "$protocol" && value=${value#*://}
+        # extract path
+        case $value in */*) path=/${value#*/} ;; esac
+        value=${value%%/*}
+        # extract username[:password]
+        case $value in *@*) username=${value%%@*} ;; esac
+        test "$username" && value=${value#*@}
+        # extract password
+        case $username in *:*) password=${username#*:} ;; esac
+        test "$password" && username=${username%%:*}
+        # finally host[:port]
+        host=$value
         ;;
     esac
 done
 
-if [ -z "$param_protocol" ] && [ -n "$param_url" ]; then
-    param_protocol=$(
-        echo "$param_url" | cut -d ':' -f 1 -s
-    )
-    if [ -z "$param_protocol" ]; then
-        unset param_protocol
-    fi
-fi
-if [ -z "$param_username" ] && [ -n "$param_url" ]; then
-    param_username=$(
-        echo "$param_url" | cut -d '/' -f 3 -s | cut -d '@' -f 1 -s | cut -d ':' -f 1
-    )
-    if [ -z "$param_username" ]; then
-        unset param_username
-    fi
-fi
-if [ -z "$param_password" ] && [ -n "$param_url" ]; then
-    param_password=$(
-        echo "$param_url" | cut -d '/' -f 3 -s | cut -d '@' -f 1 -s | cut -d ':' -f 2 -s
-    )
-    if [ -z "$param_password" ]; then
-        unset param_password
-    fi
-fi
-if [ -z "$param_host" ] && [ -n "$param_url" ]; then
-    param_host=$(
-        echo "$param_url" | cut -d '/' -f 3 -s | cut -d '@' -f 2
-    )
-    if [ -z "$param_host" ]; then
-        unset param_host
-    fi
-fi
-if [ -z "$param_path" ] && [ -n "$param_url" ]; then
-    param_path=$(
-        echo "$param_url" | cut -d '/' -f 4- -s
-    )
-    if [ -z "$param_port" ]; then
-        unset param_port
-    fi
-fi
-
 # log into lastpass if needed
 # ask for username / email address if needed
 if ! lpass status -q; then
-    if [ -z "$lpassuser" ] && [ "$LPASS_DISABLE_PINENTRY" != "1" ]; then
-        if [ -n "$LPASS_PINENTRY" ]; then
-            pinentry=$LPASS_PINENTRY
-        else
-            pinentry="pinentry"
-        fi
-        if [ -x "$(
-            unset -f command
-            command -v $pinentry
-        )" ]; then
-            lpassuser=$(
-                $pinentry <<EOF | grep '^D ' | cut -d ' ' -f 2
+    pinentry=${LPASS_PINENTRY:-pinentry}
+    if [ -z "$lpassuser" ] && [ "$LPASS_DISABLE_PINENTRY" != "1" ] &&
+        [ -x "$(unset -f command && command -v "$pinentry")" ]; then
+        lpassuser=$(
+            $pinentry <<EOF | grep '^D ' | cut -d ' ' -f 2
 SETTITLE git-credential-lastpass
 SETDESC Please enter the e-mail address for LastPass account.
 SETPROMPT e-mail address:
 GETPIN
 EOF
-            )
-        fi
-        if [ -z "$lpassuser" ]; then
-            echo "Lastpass username entry canceled" >&2
-            exit
-        fi
-    fi
-    if [ -z "$lpassuser" ] && [ -n "$LPASS_ASKPASS" ] && [ -x "$(
-        unset -f command
-        command -v $LPASS_ASKPASS
-    )" ]; then
-        lpassuser=$(
-            $LPASS_ASKPASS "e-mail address:"
         )
-        if [ -z "$lpassuser" ]; then
-            echo "Lastpass username entry canceled" >&2
-            exit
-        fi
+        test -z "$lpassuser" && echo "Lastpass username entry canceled" >&2 && exit
+    fi
+    if [ -z "$lpassuser" ] && [ -n "$LPASS_ASKPASS" ] &&
+        [ -x "$(unset -f command && command -v "$LPASS_ASKPASS")" ]; then
+        lpassuser=$($LPASS_ASKPASS "e-mail address:")
+        test -z "$lpassuser" && echo "Lastpass username entry canceled" >&2 && exit
     fi
     if [ -z "$lpassuser" ]; then
-        read -r -p "Lastpass: login required. Lastpass username: " lpassuser </dev/tty >/dev/tty
-        if [ -z "$lpassuser" ]; then
-            echo "Lastpass username entry canceled" >&2
-            exit
-        fi
+        printf "Lastpass: login required. Lastpass username: " && read -r lpassuser </dev/tty >/dev/tty
+        test -z "$lpassuser" && echo "Lastpass username entry canceled" >&2 && exit
     fi
-    if ! lpass login "$lpassuser" >&2; then
-        echo "Lastpass: failed to login" >&2
-        exit
-    fi
+    lpass login "$lpassuser" >&2 || echo "Lastpass: failed to login" >&2 && exit
+
 fi
 
-# export lastpass entries: id url username
+# export lastpass entries: entry_id entry_url entry_username entry_password
 # filter entries according to attributes: protocol, host, username, path
-ids=$(
-    lpass ls --format "%ai %al %au" | (
-        while read -r id url user; do
-            protocol=$(
-                echo "$url" | cut -d ':' -f 1 -s
-            )
-            user_pass_host_port=$(
-                echo "$url" | cut -d '/' -f 3 -s
-            )
-            # user_pass=$(
-            #     echo "$user_pass_host_port" | cut -d '@' -f 1 -s
-            # )
-            # user=$(
-            #     echo "$user_pass" | cut -d ':' -f 1
-            # )
-            # pass=$(
-            #     echo $user_pass | cut -d ':' -f 2 -s
-            # )
-            host_port=$(
-                echo "$user_pass_host_port" | cut -d '@' -f 2
-            )
-            # host=$(
-            #     echo $host_port | cut -d ':' -f 1
-            # )
-            # port=$(
-            #     echo $host_port | cut -d ':' -f 2 -s
-            # )
-            path=$(
-                echo "$url" | cut -d '/' -f 4- -s
-            )
-            # echo "$id $protocol $user $pass $host $port $path"
-            if [ -n "$param_protocol" ] && [ "$param_protocol" != "$protocol" ]; then
-                continue
-            fi
-            if [ -n "$param_host" ] && [ "$param_host" != "$host_port" ]; then
-                continue
-            fi
-            if [ -n "$param_username" ] && [ "$param_username" != "$user" ]; then
-                continue
-            fi
-            if [ -n "$param_path" ] && [ "$param_path" != "$path" ]; then
-                continue
-            fi
-            if [ -n "$path" ] && [ "$param_path" != "$path" ]; then
-                continue
-            fi
-            echo "$id"
-        done
-    )
-)
-id_count=$(echo "$ids" | wc -w)
-if [ "$id_count" -gt "1" ]; then
-    echo "More than one secret found" >&2
-    exit
-fi
-id="$ids"
+lp_entries=$(lpass ls --format "%ai %al %au %ap")
+lp_weight=0
+while read -r entry_id entry_url entry_username entry_password; do
+    if [ "$username" = "$entry_username" ] || [ ! "$username" ]; then
+        case "$entry_url" in */) entry_url=${entry_url%/} ;; esac
+        case "$entry_url" in
+        $protocol://$host*)
+            case "$protocol://$host$path" in $entry_url*)
+                entry_weight=${#entry_url}
+                if [ "$entry_weight" -gt "$lp_weight" ]; then
+                    lp_weight=$entry_weight
+                    id=$entry_id
+                    test "$username" || secret_username=$entry_username
+                    secret_password=$entry_password
+                elif [ "$lp_weight" -eq "$lp_weight" ]; then
+                    lp_weight=$entry_weight
+                    id=
+                    secret_username=
+                    secret_password=
+                fi
+                ;;
+            esac
+            ;;
+        esac
+    fi
+done <<EOF
+$lp_entries
+EOF
+test "$lp_weight" -gt 0 && test ! "$id" && echo "More than one secret found" >&2 && exit
 
 # proceed to operation
 case "$operation" in
 get)
-    if [ "$id_count" -eq "0" ]; then
-        # not found, silently exit
-        exit
+    if [ "$id" ]; then
+        test "$secret_username" && echo "username=$secret_username"
+        echo "password=$secret_password"
     fi
-    secret=$(
-        lpass show "$id"
-    )
-    secret_username=$(
-        echo "$secret" | grep Username | cut -d ' ' -f 2
-    )
-    secret_password=$(
-        echo "$secret" | grep Password | cut -d ' ' -f 2
-    )
-    echo "username=$secret_username"
-    echo "password=$secret_password"
     ;;
 store)
-    if [ "$id_count" -eq "0" ]; then
-        # not found, add
-        lastpass_protocol="$param_protocol"
-        if [ -z "$lastpass_protocol" ]; then
-            lastpass_protocol="https"
-        fi
-        lpass add --sync=no "$param_host" --non-interactive >&2 <<EOF
-URL: $lastpass_protocol://$param_host/$param_path
-Username: $param_username
-Password: $param_password
-EOF
-    else
+    if [ "$id" ]; then
         # found, edit
         lpass edit --sync=no "$id" --non-interactive >&2 <<EOF
-Username: $param_username
-Password: $param_password
+Username: $username
+Password: $password
+EOF
+    else
+        # not found, add
+        protocol=${protocol:-https}
+        lpass add --sync=no "$host" --non-interactive >&2 <<EOF
+URL: $protocol://$host$path
+Username: $username
+Password: $password
 EOF
     fi
     ;;
 erase)
-    if [ "$id_count" -eq "0" ]; then
-        # not found, silently exit
-        exit
+    if [ "$id" ]; then
+        lpass rm "$id" >&2
     fi
-    lpass rm "$id" >&2
     ;;
 esac
-
-# https://github.com/lastpass/lastpass-cli/blob/master/contrib/examples/git-credential-lastpass
-# https://github.com/lastpass/lastpass-cli/pull/587
-# https://github.com/maelvls/lastpass-cli/commits/rework-git-helper/contrib/examples/git-credential-lastpass
-# https://github.com/lastpass-cli-fork/lastpass-cli/
